// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type ChurchMinistryRoleInpt struct {
	Role *ChurchMinistryRolesEnum `json:"role,omitempty"`
}

type CreateMemberInput struct {
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Day         string  `json:"day"`
	Location    *string `json:"location,omitempty"`
	Address     *string `json:"address,omitempty"`
	LeaderType  *string `json:"leaderType,omitempty"`
	ChurchID    string  `json:"churchId"`
}

type CreateMemberInputBySub struct {
	Name        string  `json:"name"`
	Email       string  `json:"email"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Day         string  `json:"day"`
	Location    *string `json:"location,omitempty"`
	Address     *string `json:"address,omitempty"`
}

type CreateRegistrationInput struct {
	Absence     *bool   `json:"absence,omitempty"`
	LastComment *string `json:"lastComment,omitempty"`
	Present     *bool   `json:"present,omitempty"`
}

type DateInfo struct {
	Month       *string `json:"month,omitempty"`
	WeekOfMonth *int    `json:"weekOfMonth,omitempty"`
}

type EmergencyContactInput struct {
	Name        *string `json:"name,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Relation    *string `json:"relation,omitempty"`
}

type JobInfoInput struct {
	TypeOfWork     *string `json:"typeOfWork,omitempty"`
	Position       *string `json:"position,omitempty"`
	Company        *string `json:"company,omitempty"`
	WorkExperience *string `json:"workExperience,omitempty"`
}

type LeaderRegistrationsDistribution struct {
	LeaderID        string   `json:"leaderID"`
	RegistrationIDs []string `json:"registrationIDs"`
}

type LoginInput struct {
	Password    string `json:"password"`
	PhoneNumber string `json:"phoneNumber"`
}

type LoginLeaderInput struct {
	Password    string  `json:"password"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Email       *string `json:"email,omitempty"`
}

type RegistrationArrayInput struct {
	MemberID    string                   `json:"memberId"`
	CreateInput *CreateRegistrationInput `json:"createInput"`
}

type RegistrationArrayInputs struct {
	RegistrationIDs string                   `json:"registrationIDs"`
	CreateInput     *CreateRegistrationInput `json:"createInput"`
}

type RegistrationsDistribution struct {
	LeaderID        string   `json:"leaderID"`
	RegistrationIDs []string `json:"registrationIDs"`
}

type ReportRegistrationInput struct {
	Report *bool `json:"report,omitempty"`
	Done   *bool `json:"done,omitempty"`
}

type SubChurchMigrationInput struct {
	MemberID            string `json:"memberId"`
	DestinationChurchID string `json:"destinationChurchId"`
}

type WeeklyResults struct {
	Date          *DateInfo       `json:"date,omitempty"`
	Registrations []*Registration `json:"registrations,omitempty"`
}

type AssignLeaderInput struct {
	MemberID string  `json:"memberId"`
	Password *string `json:"password,omitempty"`
	Types    *string `json:"types,omitempty"`
}

type AssignSubLeaderToMemberRegistrationArrayInput struct {
	CallAgentID string   `json:"callAgentId"`
	Day         []string `json:"day"`
}

type UpdateLeaderProfileInput struct {
	Name        *string `json:"name,omitempty"`
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Oldpassword *string `json:"oldpassword,omitempty"`
	Password    *string `json:"password,omitempty"`
	Pwood       *string `json:"pwood,omitempty"`
	Location    *string `json:"location,omitempty"`
}

type UpdateMemberFamilyInfoInput struct {
	SpouseID     *string   `json:"spouseId,omitempty"`
	DateOfBirth  *string   `json:"dateOfBirth,omitempty"`
	MemberID     *string   `json:"memberID,omitempty"`
	Relationship *string   `json:"relationship,omitempty"`
	NextOfKin    *string   `json:"nextOfKin,omitempty"`
	Education    *string   `json:"education,omitempty"`
	ChildrenID   []*string `json:"childrenId,omitempty"`
}

type UpdateMemberInput struct {
	Name        *string `json:"name,omitempty"`
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	Day         *string `json:"day,omitempty"`
	Location    *string `json:"location,omitempty"`
	Pwood       *string `json:"pwood,omitempty"`
}

type ChurchMinistryRolesEnum string

const (
	ChurchMinistryRolesEnumPastor              ChurchMinistryRolesEnum = "PASTOR"
	ChurchMinistryRolesEnumRaven               ChurchMinistryRolesEnum = "RAVEN"
	ChurchMinistryRolesEnumBishop              ChurchMinistryRolesEnum = "BISHOP"
	ChurchMinistryRolesEnumSecurity            ChurchMinistryRolesEnum = "SECURITY"
	ChurchMinistryRolesEnumSundaySchoolTeacher ChurchMinistryRolesEnum = "SUNDAY_SCHOOL_TEACHER"
	ChurchMinistryRolesEnumFinance             ChurchMinistryRolesEnum = "FINANCE"
	ChurchMinistryRolesEnumUsher               ChurchMinistryRolesEnum = "USHER"
	ChurchMinistryRolesEnumMusic               ChurchMinistryRolesEnum = "MUSIC"
	ChurchMinistryRolesEnumDomestic            ChurchMinistryRolesEnum = "DOMESTIC"
	ChurchMinistryRolesEnumMedia               ChurchMinistryRolesEnum = "MEDIA"
)

var AllChurchMinistryRolesEnum = []ChurchMinistryRolesEnum{
	ChurchMinistryRolesEnumPastor,
	ChurchMinistryRolesEnumRaven,
	ChurchMinistryRolesEnumBishop,
	ChurchMinistryRolesEnumSecurity,
	ChurchMinistryRolesEnumSundaySchoolTeacher,
	ChurchMinistryRolesEnumFinance,
	ChurchMinistryRolesEnumUsher,
	ChurchMinistryRolesEnumMusic,
	ChurchMinistryRolesEnumDomestic,
	ChurchMinistryRolesEnumMedia,
}

func (e ChurchMinistryRolesEnum) IsValid() bool {
	switch e {
	case ChurchMinistryRolesEnumPastor, ChurchMinistryRolesEnumRaven, ChurchMinistryRolesEnumBishop, ChurchMinistryRolesEnumSecurity, ChurchMinistryRolesEnumSundaySchoolTeacher, ChurchMinistryRolesEnumFinance, ChurchMinistryRolesEnumUsher, ChurchMinistryRolesEnumMusic, ChurchMinistryRolesEnumDomestic, ChurchMinistryRolesEnumMedia:
		return true
	}
	return false
}

func (e ChurchMinistryRolesEnum) String() string {
	return string(e)
}

func (e *ChurchMinistryRolesEnum) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChurchMinistryRolesEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChurchMinistryRolesEnum", str)
	}
	return nil
}

func (e ChurchMinistryRolesEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MigrationStatus string

const (
	MigrationStatusPending   MigrationStatus = "PENDING"
	MigrationStatusApproved  MigrationStatus = "APPROVED"
	MigrationStatusRejected  MigrationStatus = "REJECTED"
	MigrationStatusCompleted MigrationStatus = "COMPLETED"
)

var AllMigrationStatus = []MigrationStatus{
	MigrationStatusPending,
	MigrationStatusApproved,
	MigrationStatusRejected,
	MigrationStatusCompleted,
}

func (e MigrationStatus) IsValid() bool {
	switch e {
	case MigrationStatusPending, MigrationStatusApproved, MigrationStatusRejected, MigrationStatusCompleted:
		return true
	}
	return false
}

func (e MigrationStatus) String() string {
	return string(e)
}

func (e *MigrationStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MigrationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MigrationStatus", str)
	}
	return nil
}

func (e MigrationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
